services:
  - type: web
    name: email-scheduler-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build:backend
    startCommand: npm run start:backend
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://email-scheduler-frontend-zeta.vercel.app
      - key: GOOGLE_CALLBACK_URL
        value: https://email-scheduler-tehc.onrender.com/api/auth/google/callback
      - key: GOOGLE_CLIENT_ID
        value: 862591490941-nb6hjuik2iohg7kvj4vt0v3p6rbdad16.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        value: 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
      - key: START_WORKER
        value: "true"
      - key: MYSQL_SSL
        value: "true"
      - key: SESSION_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: SMTP_HOST
        value: smtp.ethereal.email
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: "false"
      - key: SMTP_USER
        value: do5pnebti5pc256m@ethereal.email
      - key: SMTP_PASSWORD
        value: XEX1dkjSVrpX3vWA4Q
